import { type FormEvent, useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { AuthGate, AuthOverlay, useAuthProfileReady, useQuery } from 'deepspace'
import { CalendarDays, Check, CloudSun, Compass, Copy, ExternalLink, LoaderCircle, MapPin, Sparkles, Users } from 'lucide-react'
import { Button, Input, Textarea, useToast } from '@/components/ui'
import { callAction, localIsoDate } from '@/lib/trip-client'

type WeatherPoint = { dt: number; temp: number; description: string }
type Trip = { title: string; destination: string; startDate: string; endDate: string; preferences: string; memberIds: string[]; inviteCode: string; weatherJson: WeatherPoint[]; itineraryStatus?: 'draft' | 'published' }
type Activity = { tripId: string; title: string; sourceUrl: string; sourceName: string; snippet: string }
type Vote = { activityId: string; voterId: string }
type Itinerary = { content: string; status?: 'draft' | 'published' }
type FormData = { title: string; destination: string; startDate: string; endDate: string; preferences: string }

const initialForm = (): FormData => ({ title: 'A small weekend escape', destination: '', startDate: localIsoDate(1), endDate: localIsoDate(2), preferences: 'easygoing, outdoors, local culture' })

export default function HomePage() {
  return <AuthGate fallback={<PlannerSignIn />}><PlannerPage /></AuthGate>
}

function PlannerPage() {
  const { user } = useAuthProfileReady({ requireUser: true })
  const { success, error } = useToast()
  const [searchParams, setSearchParams] = useSearchParams()
  const [form, setForm] = useState<FormData>(initialForm)
  const [showForm, setShowForm] = useState(false)
  const [selectedTripId, setSelectedTripId] = useState('')
  const [pending, setPending] = useState<string | null>(null)
  const { records: trips, status: tripStatus } = useQuery<Trip>('trips', { orderBy: 'createdAt', orderDir: 'desc', limit: 50 })

  useEffect(() => {
    const fromInvite = searchParams.get('trip')
    if (fromInvite && trips.some((trip) => trip.recordId === fromInvite)) {
      setSelectedTripId(fromInvite)
      setSearchParams({}, { replace: true })
    } else if (!selectedTripId && trips[0]) setSelectedTripId(trips[0].recordId)
  }, [selectedTripId, searchParams, setSearchParams, trips])

  const trip = trips.find((row) => row.recordId === selectedTripId)
  const isFinal = trip?.data.itineraryStatus === 'published'
  const isOrganizer = trip?.createdBy === user?.id
  const { records: activities, status: activityStatus } = useQuery<Activity>('activityCards', { where: { tripId: selectedTripId || '__none__' }, orderBy: 'createdAt', orderDir: 'asc', limit: 20 })
  const { records: votes } = useQuery<Vote>('votes', { where: { tripId: selectedTripId || '__none__' }, limit: 100 })
  const { records: itineraries } = useQuery<Itinerary>('itineraries', { where: { tripId: selectedTripId || '__none__' }, limit: 1 })
  const counts = useMemo(() => { const next = new Map<string, number>(); votes.forEach((vote) => next.set(vote.data.activityId, (next.get(vote.data.activityId) ?? 0) + 1)); return next }, [votes])

  async function run<T>(name: string, input: Record<string, unknown>, done?: (data: T) => void) {
    setPending(name)
    const result = await callAction<T>(name, input)
    setPending(null)
    if (result.success) done?.(result.data)
    else error('Couldn’t complete that', result.error)
  }

  function submit(event: FormEvent) {
    event.preventDefault()
    void run<{ tripId: string }>('createTrip', form, ({ tripId }) => { setSelectedTripId(tripId); setShowForm(false); setForm(initialForm()); success('Board created', 'Invite your group, then discover a small set of ideas.') })
  }

  function copyInvite() {
    if (!trip) return
    void navigator.clipboard.writeText(`${window.location.origin}/join/${trip.data.inviteCode}`).then(() => success('Invite link copied', 'Anyone who signs in through this link joins this private board.'), () => error('Copy failed', 'Share the URL from your browser address bar instead.'))
  }

  if (tripStatus === 'loading') return <Loading label="Opening your shared planning boards…" />
  return <div className="min-h-full bg-[radial-gradient(circle_at_10%_0%,rgba(129,140,248,.18),transparent_32%),radial-gradient(circle_at_90%_20%,rgba(16,185,129,.1),transparent_24%)]"><section className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12">
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-primary"><Compass className="h-4 w-4" /> group getaway planning</p><h1 className="max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Make one good plan, together.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">A few sourced activity ideas, live group votes, and one weather-aware plan—without the endless group chat.</p></div><Button onClick={() => setShowForm((open) => !open)} variant={showForm ? 'outline' : 'default'}>{showForm ? 'Close setup' : 'New getaway'}</Button></div>
    {showForm && <TripSetup form={form} setForm={setForm} submit={submit} loading={pending === 'createTrip'} />}
    {!trip && !showForm && <EmptyBoard open={() => setShowForm(true)} />}
    {trip && <div className="mt-8 space-y-6">
      <TripHeader trip={trip.data} tripId={trip.recordId} trips={trips.map((row) => ({ id: row.recordId, title: row.data.title }))} select={setSelectedTripId} copy={copyInvite} />
      <div className="grid gap-6 lg:grid-cols-[minmax(0,1.65fr)_minmax(280px,.75fr)]"><section className="min-w-0 space-y-5"><div className="flex flex-col gap-3 rounded-2xl border border-border bg-card/80 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><CloudSun className="h-5 w-5 text-warning" /><div><p className="font-medium">{isOrganizer ? 'Find a few credible activity ideas' : 'Vote on the organizer’s activity ideas'}</p><p className="text-xs text-muted-foreground">{isOrganizer ? 'Search is capped at six sourced cards for an unchanged trip brief.' : activities.length === 0 ? 'The organizer is gathering ideas—check back soon.' : 'Your votes shape the itinerary the organizer publishes.'}</p></div></div>{isOrganizer && <Button size="sm" disabled={isFinal} loading={pending === 'discoverActivities'} onClick={() => void run<{ cached: boolean; count: number }>('discoverActivities', { tripId: trip.recordId }, (data) => success(data.cached ? 'Ideas already current' : 'Fresh ideas are ready', data.cached ? 'Change the brief to discover again.' : `${data.count} sources are ready for the group.`))}><Sparkles /> Discover ideas</Button>}</div>
        {activityStatus === 'loading' ? <Loading label="Syncing activity ideas…" compact /> : activities.length === 0 ? <NoActivities /> : <div className="grid gap-4 md:grid-cols-2">{activities.map((activity) => { const count = counts.get(activity.recordId) ?? 0; const voted = votes.some((vote) => vote.data.activityId === activity.recordId && vote.data.voterId === user?.id); return <ActivityCard key={activity.recordId} activity={activity.data} votes={count} voted={voted} locked={isFinal} loading={pending === `vote:${activity.recordId}`} onVote={() => void run<{ voted: boolean }>('toggleVote', { activityId: activity.recordId }, (data) => success(data.voted ? 'Vote added' : 'Vote removed', 'Your group sees this change immediately.'))} /> })}</div>}
      </section><aside className="space-y-5"><WeatherCard points={trip.data.weatherJson} /><ItineraryControls final={isFinal} organizer={isOrganizer} hasItinerary={Boolean(itineraries[0])} canGenerate={activities.length > 0} generating={pending === 'generateItinerary'} publishing={pending === 'publishItinerary'} unlocking={pending === 'unlockItinerary'} onGenerate={() => void run<{ cached: boolean }>('generateItinerary', { tripId: trip.recordId }, (data) => success(data.cached ? 'Itinerary already current' : 'Draft itinerary ready', data.cached ? 'The group’s selected cards have not changed.' : 'Review the draft, then have the organizer publish it.'))} onPublish={() => void run<{ alreadyPublished: boolean }>('publishItinerary', { tripId: trip.recordId }, () => success('Itinerary published', 'The final plan is now locked for the group.'))} onUnlock={() => void run<{ unlocked: boolean }>('unlockItinerary', { tripId: trip.recordId }, () => success('Planning unlocked', 'Members can update votes and create a new draft.'))} /></aside></div>
      {itineraries[0] && <ItineraryCard itinerary={itineraries[0].data} final={isFinal} />}
    </div>}
  </section></div>
}

function TripSetup({ form, setForm, submit, loading }: { form: FormData; setForm: React.Dispatch<React.SetStateAction<FormData>>; submit: (event: FormEvent) => void; loading: boolean }) { const today = localIsoDate(); const lastDay = localIsoDate(4); return <form onSubmit={submit} className="mt-8 grid gap-4 rounded-3xl border border-border bg-card p-5 sm:grid-cols-2 sm:p-7"><div className="sm:col-span-2"><h2 className="text-lg font-semibold">Set a compact trip brief</h2><p className="mt-1 text-sm text-muted-foreground">Dates stay inside the live five-day forecast window—an intentional limit, not a hidden promise.</p></div><Field label="Board name"><Input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></Field><Field label="Destination"><Input required placeholder="e.g. Santa Cruz, CA" value={form.destination} onChange={(event) => setForm({ ...form, destination: event.target.value })} /></Field><Field label="Start date"><Input required type="date" min={today} max={lastDay} value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></Field><Field label="End date"><Input required type="date" min={today} max={lastDay} value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></Field><div className="sm:col-span-2"><Field label="What kind of day are you hoping for?"><Textarea required rows={3} value={form.preferences} onChange={(event) => setForm({ ...form, preferences: event.target.value })} /></Field></div><div className="sm:col-span-2 flex justify-end"><Button type="submit" loading={loading}>Create private board</Button></div></form> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span>{children}</label> }
function TripHeader({ trip, trips, tripId, select, copy }: { trip: Trip; trips: { id: string; title: string }[]; tripId: string; select: (id: string) => void; copy: () => void }) { return <div className="overflow-hidden rounded-3xl border border-border bg-card shadow-[0_18px_55px_rgba(0,0,0,.18)]"><div className="bg-[linear-gradient(110deg,rgba(99,102,241,.32),rgba(16,185,129,.14))] p-6 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary-foreground/80">Active board</p><h2 className="mt-2 text-2xl font-semibold">{trip.title}</h2><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm text-foreground/80"><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" />{trip.destination}</span><span className="flex items-center gap-1.5"><CalendarDays className="h-4 w-4" />{trip.startDate} → {trip.endDate}</span><span className="flex items-center gap-1.5"><Users className="h-4 w-4" />{trip.memberIds.length} member{trip.memberIds.length === 1 ? '' : 's'}</span></div></div><Button variant="secondary" size="sm" onClick={copy}><Copy /> Copy invite</Button></div></div><div className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center"><span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Switch board</span><select aria-label="Switch planning board" className="h-9 flex-1 rounded-md border border-input bg-background px-3 text-sm" value={tripId} onChange={(event) => select(event.target.value)}>{trips.map((option) => <option key={option.id} value={option.id}>{option.title}</option>)}</select></div></div> }
function ActivityCard({ activity, votes, voted, locked, loading, onVote }: { activity: Activity; votes: number; voted: boolean; locked: boolean; loading: boolean; onVote: () => void }) { return <article className="flex min-h-60 flex-col overflow-hidden rounded-2xl border border-border bg-card transition-transform hover:-translate-y-0.5"><div className="p-5"><div className="flex items-start justify-between gap-3"><p className="text-xs font-medium text-primary">{activity.sourceName}</p><a href={activity.sourceUrl} target="_blank" rel="noreferrer" aria-label={`Open source for ${activity.title}`} className="text-muted-foreground hover:text-foreground"><ExternalLink className="h-4 w-4" /></a></div><h3 className="mt-2 font-semibold leading-5">{activity.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{activity.snippet}</p></div><div className="mt-auto flex items-center justify-between border-t border-border px-4 py-3"><span className="text-xs text-muted-foreground">{votes} group vote{votes === 1 ? '' : 's'}</span><Button size="sm" disabled={locked} variant={voted ? 'secondary' : 'outline'} loading={loading} onClick={onVote}>{voted ? <><Check /> Voted</> : 'Vote for this'}</Button></div></article> }
function WeatherCard({ points }: { points: WeatherPoint[] }) { const first = points[0]; return <div className="rounded-2xl border border-border bg-card p-5"><p className="flex items-center gap-2 font-medium"><CloudSun className="h-4 w-4 text-warning" /> Forecast signal</p>{first ? <><p className="mt-3 text-3xl font-semibold">{Math.round(first.temp)}°F</p><p className="mt-1 text-sm capitalize text-muted-foreground">{first.description}</p><p className="mt-4 text-xs leading-5 text-muted-foreground">Forecast is sampled from the next five days and shapes the plan—not a promise about conditions.</p></> : <p className="mt-3 text-sm leading-6 text-muted-foreground">Discover activities to fetch the forecast for this destination.</p>}</div> }
function ItineraryControls({ final, organizer, hasItinerary, canGenerate, generating, publishing, unlocking, onGenerate, onPublish, onUnlock }: { final: boolean; organizer: boolean; hasItinerary: boolean; canGenerate: boolean; generating: boolean; publishing: boolean; unlocking: boolean; onGenerate: () => void; onPublish: () => void; onUnlock: () => void }) { if (final) return <div className="rounded-2xl border border-success/30 bg-success/[.08] p-5"><p className="flex items-center gap-2 font-medium text-success"><Check className="h-4 w-4" /> Final itinerary</p><p className="mt-2 text-sm leading-6 text-muted-foreground">This plan is locked so the group has one clear decision.</p>{organizer && <Button className="mt-4 w-full" variant="outline" loading={unlocking} onClick={onUnlock}>Unlock planning</Button>}</div>; if (!organizer) return <div className="rounded-2xl border border-primary/30 bg-primary/[.08] p-5"><p className="flex items-center gap-2 font-medium"><Sparkles className="h-4 w-4 text-primary" /> Itinerary status</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Vote on the activities you want. The organizer will turn the group’s choices into a shared itinerary.</p></div>; return <div className="rounded-2xl border border-primary/30 bg-primary/[.08] p-5"><p className="flex items-center gap-2 font-medium"><Sparkles className="h-4 w-4 text-primary" /> Organizer controls</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Build a draft from group votes, then publish one final plan for everyone.</p><Button className="mt-4 w-full" disabled={!canGenerate} loading={generating} onClick={onGenerate}>Build draft itinerary</Button><Button className="mt-2 w-full" variant="secondary" disabled={!hasItinerary} loading={publishing} onClick={onPublish}>Publish final itinerary</Button></div> }
function ItineraryCard({ itinerary, final }: { itinerary: Itinerary; final: boolean }) { return <section className="rounded-3xl border border-success/30 bg-success/[.06] p-6 sm:p-8"><p className="flex items-center gap-2 text-sm font-medium text-success"><Sparkles className="h-4 w-4" /> {final ? 'Final itinerary' : 'Shared draft'}</p><pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-7">{itinerary.content}</pre><p className="mt-5 text-xs text-muted-foreground">{final ? 'This is the organizer-published group decision. The organizer can unlock planning if it needs to change.' : 'This draft is based only on voted source cards and the current forecast. Confirm logistics directly with each source.'}</p></section> }
function EmptyBoard({ open }: { open: () => void }) { return <div className="mt-8 rounded-3xl border border-dashed border-border bg-card/50 px-6 py-16 text-center"><Compass className="mx-auto h-9 w-9 text-primary" /><h2 className="mt-4 text-xl font-semibold">Start with one small escape</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Create a board, bring your group in with one private link, and use live votes to avoid the endless group chat.</p><Button className="mt-6" onClick={open}>Create a getaway</Button></div> }
function NoActivities() { return <div className="rounded-2xl border border-dashed border-border p-10 text-center"><MapPin className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 font-medium">No activity cards yet</p><p className="mt-1 text-sm text-muted-foreground">Run discovery to collect a small, sourced set for the group to vote on.</p></div> }
function Loading({ label, compact = false }: { label: string; compact?: boolean }) { return <div className={`flex items-center justify-center gap-2 text-sm text-muted-foreground ${compact ? 'rounded-2xl border border-border p-10' : 'min-h-[50vh]'}`}><LoaderCircle className="h-4 w-4 animate-spin" />{label}</div> }
function PlannerSignIn() { const [open, setOpen] = useState(false); return <div className="mx-auto flex min-h-[70vh] max-w-lg items-center px-6"><div className="w-full rounded-3xl border border-border bg-card p-8 text-center"><Compass className="mx-auto h-9 w-9 text-primary" /><h1 className="mt-4 text-xl font-semibold">Your group board is private</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Sign in to create or join a Roam Consensus board. Shared activity cards, votes, and itineraries are only visible to invited members.</p><Button className="mt-6" onClick={() => setOpen(true)}>Sign in to plan</Button>{open && <AuthOverlay onClose={() => setOpen(false)} />}</div></div> }
